- name: Play 1
  hosts: localhost
  tasks:

     - name: Who am I
       ansible.builtin.command: whoami
       register: _command

     - name: debug
       ansible.builtin.debug:
         var: _command
