id: RELOAD-HTTP-STATUS
namespace: reloaddata

inputs:
  - id: uri
    type: URI
    required: true
    defaults:
      - "https://google.com"

tasks:
  - id: api
    type: io.kestra.plugin.fs.http.Request
    uri: "{{ inputs.uri }}"

  - id: check_status
    type: io.kestra.core.tasks.flows.If
    condition: "{{ outputs.api.code != 200 }}"
    then:
      - id: logError
        type: io.kestra.core.tasks.log.Log
        message: "⚠️ There's an error, sending message to Discord.⚠️"
      - id: DiscordMessage
        type: io.kestra.plugin.notifications.discord.DiscordIncomingWebhook
        url: "{{ secret('DISCORD_WEBHOOK')}}"
        payload: |
          {
            "username": "Kestra",
            "content": "Monitoring alert for flow {{flow.namespace}}. {{flow.id}} request to {{inputs.url}} failed with: {{outputs.pythonscript.vars.status_code}}"
          }
    else:
      - id: logSuccessful
        type: io.kestra.core.tasks.log.Log
        message: "Everything is okay 👍."
triggers:
  - id: schedule_trigger
    type: io.kestra.core.models.triggers.types.Schedule
    cron: '*/30 * * * *'
    inputs: {url: 'https://reloaddata.app'}